require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "bash",
    "vue",
    -- "c",
    -- "cpp",
    "css",
    -- "elixir",
    -- "fish",
    "graphql",
    "html",
    "javascript",
    "json",
    "lua",
    "markdown",
    "markdown_inline",
    -- "php",
    -- "python",
    -- "regex",
    -- "ruby",
    -- "rust",
    "scss",
    "sql",
    -- "toml",
    "tsx",
    "typescript",
    "vim",
    "yaml",
  },
  autopairs = {
		enable = true,
	},
  highlight = { enable = true },
  indent = { enable = true },
  autotag = {
  enable = true,
  filetypes = {
    "html",
    "javascript",
    "javascriptreact",
    "svelte",
    "typescript",
    "typescriptreact",
    "vue",
    "xml",
    },
  },
})
